# Site settings
title: David's Blog
email: 
description: ""
baseurl: "daviddao.de/blog/"
url: 
twitter_username: daviddao_
github_username: daviddao

# Build settings
markdown: redcarpet
permalink: pretty
