name: Download scholar
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1-31 * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Download scholar
        working-directory: ./scholar-crawler
        run: cargo run
      - name: Commit data
        run: |
          git config --global user.name 'David Dao'
          git config --global user.email 'david@gainforest.net'
          git add -A
          git commit -am "Automated scholar data commit"
          git push
